version: '3'
services:
  postgres:
    image: 'postgres:9.6-alpine'
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      # - "postgres:/var/lib/postgresql/data"
      #- "postgres:/var/lib/postgresql-9.6/data"
      - /home/igor/workspace/database/postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "5051:80"
    depends_on:
      - postgres
    

  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid; bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/cnabapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres:
