default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres
  password: mypassword

development:
  <<: *default
  database: cnab_dev

test:
  <<: *default
  database: cnab_test